### PR TITLE
Add support for uStreamer 5.x

### LINKED ISSUE #58: Add support for `m2m-image` encoder
uStreamer 5.x dropped the OMX encoder and replaces it with the M2M encoder. It looks like M2M is compiled by default, so I don't think there's a special compilation flag.

### PR DESCRIPTION
**Pull request by mtlynch**
Debian's APIs for accessing the GPU changed between Debian Buster (10) and Debian Bullseye (11). uStreamer 4.x relied on the omx APIs for accessing the GPU, but those disappeared in Bullseye and were replaced by m2m APIs. uStreamer 5.x relies on the m2m APIs, which are not available in Debian Buster.

|                       | Debian Buster (and earlier) | Debian Bullseye |
|---------------|-----------------------------|-----------------|
| uStreamer 4.x | Full compatibility | omx-based encoding doesn't work |
| uStreamer 5.x | m2m-based encoding doesn't work | Full compatibility |

This change adjusts uStreamer's options so that the role now defaults to uStreamer 5.x semantics if the client does not specify a version of uStreamer to use. The role still supports uStreamer 4.x semantics if the client specifies uStreamer 4.x and the target OS supports the options.

This also splits our molecule tests into "legacy" tests for uStreamer 4.x-compatible OS versions and "default" tests for uStreamer 5.x-compatible OS versions.

Fixes #58 

Related: https://github.com/tiny-pilot/ansible-role-tinypilot/pull/222

Tested on Raspbian Buster and Bullseye with a TC358743 capture chip.

### CODE REVIEW

**Comment by mtlynch** [comment]
Everything compiles, but I'm seeing "Persistent device timeout (unplugged)" when I actually run it on Bullseye with a TC358743:

https://gist.github.com/mtlynch/43ddc71e8b83db313a359f98c6bb7775

The same setup works on Buster with 4.x, so I'm not sure what's going wrong.

**Comment by mtlynch** [comment]
Okay, got it working now. There's an odd thing where you have to manually reload the EDID after boot because it seems to fail on first run with Bullseye for some reason:

```bash
$ sudo journalctl -u load-tc358743-edid
-- Journal begins at Tue 2022-09-06 15:06:18 EDT, ends at Fri 2022-09-23 17:27:15 EDT. --
Sep 23 09:31:27 raspberrypi systemd[1]: Starting Load EDID for TC358743 HDMI capture chip....
Sep 23 09:31:27 raspberrypi v4l2-ctl[12278]: Cannot open device /dev/video0, exiting.
Sep 23 09:31:27 raspberrypi systemd[1]: load-tc358743-edid.service: Main process exited, code=exited, status=1/FAILURE
Sep 23 09:31:27 raspberrypi systemd[1]: load-tc358743-edid.service: Failed with result 'exit-code'.
Sep 23 09:31:27 raspberrypi systemd[1]: Failed to start Load EDID for TC358743 HDMI capture chip..
```

Workaround:

```bash
 sudo service load-tc358743-edid start && sudo service ustreamer restart
```

**Comment by mtlynch** [comment]
Slightly better workaround.

Add this line to `/lib/systemd/system/ustreamer.service` in the `[Unit]` section:

```text
After=syslog.target network.target boot-complete.target load-tc358743-edid.service
```

Add this line to ` /lib/systemd/system/load-tc358743-edid.service` in the `[Service]` section:

```text
Restart=on-failure
```

**Comment by mtlynch** [comment]
Even with the workarounds in place, uStreamer still sometimes gets:

```text
ERROR [131.901    stream] -- Persistent device timeout (unplugged)
```

And then running `sudo service load-tc358743-edid start` fixes it.

It doesn't actually seem like uStreamer has to start after `load-tc358743-edid` because loading the EDID while uStreamer is already running works.

**Comment by mtlynch** [comment]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/63)

⏳ @jdeanwallace please review this Pull Request

**Review by jdeanwallace — CHANGES_REQUESTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/63)


Approved on CodeApprove
✔️ Approved (4 unresolved comments)

<hr />

In: **Discussion**
Can we adjust [this comment](https://github.com/tiny-pilot/ansible-role-ustreamer/blob/0834d029360cd9fd49d78bbc0559b073b603ccbb/defaults/main.yml#L84-L85) about H264 sink options only being available when OpenMax is enabled? This is now only true on Buster or earlier.

<hr />

In: **molecule/default/converge.yml**:

```
> Line 13
        ustreamer_repo_version: "v5.22"
```
uStreamer `v5.23` has been released a couple days ago. Can we bump the version here and in our uStreamer fork?

<hr />

In: **tasks/main.yml**:

```
> Line 62
              (ansible_distribution_major_version | int) <= 10)) }}
```
It would be cool if could short circuit these complicated conditions with a uStreamer version check. Ironically this would make the condition even more complex.

Perhaps using something like (untested):
```
{{ ustreamer_repo_version is version('v5', '<') }}
```

<hr />

In: **tasks/provision_tc358743.yml**:

```
> Line 65
          ((ansible_distribution_major_version | int) <= 10)
```
Can we also stop [specifying `ustreamer_encoder=omx` in our bundle installer](https://github.com/tiny-pilot/tinypilot/blob/59e73d15f456cfcb31703937c0a48d2c297da335/bundler/bundle/install#L78)?

We need to do this at some point to avoid triggering our "check that OpenMax IL acceleration is only compiled on Raspberry Pi OS 10 (Buster) and earlier" trap.


<hr />

👀 @mtlynch it's your turn please take a look

**Review by mtlynch — COMMENTED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/63)



<hr />

In: **Discussion**
Sure, updated.

<hr />

In: **molecule/default/converge.yml**:
Sure, done.

<hr />

In: **tasks/main.yml**:
I'm a little skittish about using `version` since it's not clear from [the docs](https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#comparing-versions) how it handles the `v` prefix. It also wouldn't work if ansible_repo_version was a non-versioned branch name. But I agree about the complexity, so I've refactored it into a `ustreamer_os_supports_omx` fact, which I think simplifies later conditions.

<hr />

In: **tasks/provision_tc358743.yml**:
Oh, good point. I've added a bug:

https://github.com/tiny-pilot/tinypilot/issues/1110

**Review by jdeanwallace — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/63)

Approved: I have approved this change on CodeApprove and all of my comments have been resolved.

**Pull request merged**
