### PR TITLE
Update to the new EDID

### PR DESCRIPTION
**Pull request by db39**
This change is a result of our [EDID investigation](https://github.com/tiny-pilot/tinypilot-pro/issues/637), and our [plan for
integrating the EDID](https://github.com/tiny-pilot/tinypilot-pro/issues/637#issuecomment-1312217260) into TinyPilot.

The Toshiba TC358743 chip can support and capture more resolutions than
TinyPilot previously advertised to output devices using its original EDID.

This new EDID improves compatibility with HDMI output devices, allowing
TinyPilot to capture and display ~2x more resolutions and refresh rates
compared to the previous EDID.

This change removes the following display timings from the EDID due to
incompatibility:

- 720x576 at 50Hz

This change adds the following display timings to the EDID:

- 1600x900 at 60Hz
- 1280x1024 at 75Hz and 60Hz
- 1440x900 at 60Hz
- 1280x960 at 60Hz
- 1280x800 at 60Hz
- 1152x864 at 75Hz
- 1024x768 at 75Hz, 70Hz, and 60Hz
- 832x624 at 75Hz
- 800x600 at 72.25Hz, 75Hz, 60Hz, and 56.25Hz
- 640x480 at 75Hz, 72.75Hz, 66.67Hz, and 60Hz
- 720x400 at 87.85Hz

`TinyPilot` is now set as the device's display name: improving the UX when
viewing the device in the target computer's display settings. This
replaces the previous device name of `Toshiba-H2C` which was potentially
confusing to end users.

We set a new default preferred resolution & refresh rate - 1920x1080 at 30Hz -
replacing the old preferred timing of 1280x720 at 60Hz.
This removes the need for users to manually change the display settings from
720p to 1080p in common scenarios.

<a data-ca-tag href="https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/93">Review on CodeApprove</a>

### CODE REVIEW

**Comment by mtlynch** [comment]
@db39 - Can you add more details here just so we remember the context if we revisit this commit later?

**Comment by db39** [comment]
This change is a result of our [EDID investigation](https://github.com/tiny-pilot/tinypilot-pro/issues/637), and our [plan for integrating the EDID](https://github.com/tiny-pilot/tinypilot-pro/issues/637#issuecomment-1312217260) into TinyPilot.

This change replaces TinyPilot's original default EDID:

```text
00ffffffffffff005262888800888888
2d1e0103800000780aee91a3544c9926
0f505400000001010101010101010101
010101010101011d007251d01e206e28
5500c48e2100001e8c0ad08a20e02d10
103e9600138e2100001e000000fc0054
6f73686962612d4832430a20000000fd
003b3d0f2e0f1e0a2020202020200135
020321434e041303021211012021a23c
3d3e1f2309070766030c00300080e300
7f8c0ad08a20e02d10103e9600c48e21
0000188c0ad08a20e02d10103e960013
8e210000188c0aa01451f01600267c43
00138e21000098000000000000000000
00000000000000000000000000000000
00000000000000000000000000000028
```

| Resolution | Refresh rates (Hz) |
| ---------- | ------------------ |
| 1920x1080  | 50, 30, 25, 24     |
| 1280x720   | 60, 50, 30, 25, 24 |
| 720x480    | 60                 |
| 720x576    | 50                 |
| 640x480    | 60                 |


With a new EDID that supports more display settings:

```text
00ffffffffffff005262888800888888
2d1e0103800000781aee91a3544c9926
0f50547fef8081c08140810081809500
a9c081406140271f80f07138164038c0
350040442100001eec2c80a070381a40
3020350040442100001e000000fc0054
696e7950696c6f740a202020000000fd
003b3d0f2e1000000000000000000147
02031c734c010204139f2021223c3d3e
3c2066030c00300080e2007f00000000
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
0000000000000000000000000000006b
```

| Resolution |  Refresh rates (Hz)  |
| ---------- | -------------------- |
| 1920x1080  | 50, 30, 25, 24       |
| 1600x900   | 60                   |
| 1280x1024  | 75, 60               |
| 1440x900   | 60                   |
| 1280x960   | 60                   |
| 1280x800   | 60                   |
| 1152x864   | 75                   |
| 1280x720   | 60, 50, 30, 25, 24   |
| 1024x768   | 75, 70, 60           |
| 832x624    | 75                   |
| 800x600    | 72.25, 75, 60, 56.25 |
| 720x480    | 60                   |
| 640x480    | 75, 72.75, 66.67, 60 |
| 720x400    | 87.85                |

In addition to the new supported display settings, the EDID now contains `tinypilot` as the device name and sets the preferred display setting to 1080p, 30Hz, instead of the previous 720p, 60Hz.

**Comment by mtlynch** [comment]
@db39 - Can you move the explanation to the PR description? That's what gets preserved in the commit.

Can we also revise it to focus more on the [why than the how](https://cbea.ms/git-commit/#why-not-how)? We can cut the binary blobs because those are in the commit itself and don't really mean anything to human readers. Aside from the "before it was X, now it's Y," I'd like to cover:

* What are the important deltas?
* Why are we making these changes?

**Comment by db39** [comment]
@mtlynch, thanks for guidance! I've update the PR description with an updated explanation - how does that look now?

**Comment by mtlynch** [comment]
Can we add in a few more details:

* What was the preferred timing before?
* What was the name before?
* What are the timings we're adding?
* Are we deleting any timings?

**Comment by db39** [comment]
Done! I've added info for the previous device name, previous preferred timing, removed timings, and additional timings.

**Review by mtlynch — APPROVED** [review]
##### Automated comment from [CodeApprove ➜](https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/93)


<a href="https://codeapprove.com/pr/tiny-pilot/ansible-role-ustreamer/93">Approved on CodeApprove</a>
✔️ Approved

LGTM, thanks!

<hr />

👀 @db39 it's your turn please take a look

**Comment by mtlynch** [comment]
@db39 - This is all set for you to merge.

**Pull request merged**
